import UIProvider from "@/src/components/providers/UIProvider";
import "@/src/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<UIProvider>
					<Toaster />
					{/* <ThemeSwitcher /> */}
					{children}
				</UIProvider>
			</body>
		</html>
	);
}
